### DISCUSSION TITLE
How to manipulate the environment before topgrade uses it, or override command paths?

### DISCUSSION THREAD

**Discussion by jchonig** [topgrade-rs/topgrade#582] [Q&A] [answered]
I have a personal bin directory that has some commands that conflict with commands that topgrade expects.  There are two ways I could see to address this, are either of them implemented?

A config command that allows manipulation of the PATH environment variable before topgrade reads it.
```toml
[pre_command]
"ENV_PATH" = "export PATH $(echo $PATH | sed -re \"s%${HOME}/bin[^:]*:%:%g")\"
```

The ability to specify the full path of a command to run for any step:
```toml
[gem]
bin_path = "/usr/bin/gem"
```

Thanks.

Jeff
