### DISCUSSION TITLE
unknown field `pull_only_repos`

### DISCUSSION THREAD

**Discussion by musicfunfan** [topgrade-rs/topgrade#681] [Q&A] [answered]
Hello there, I need help with my config. 

I use the same config file for topgrade for some time now. And was working fine. My problem is that now when i run ``topgrade -c`` I get this error 
```bash 
❯ topgrade -c 
ERROR Failed to deserialize /home/musicfan/.config/topgrade.toml: TOML parse error at line 44, column 1
   |
44 | pull_only_repos = [ 
   | ^^^^^^^^^^^^^^^
unknown field `pull_only_repos`, expected one of `max_concurrency`, `arguments`, `repos`, `pull_predefined`  
```
My config of topgrade can be found [here](https://gitlab.com/musicfunfan/main_configs_files/-/blob/main/topgrade/topgrade.toml?ref_type=heads). 

The block that failing is this. 

```toml
[git]
max_concurrency = 5
# Additional git repositories to pull
pull_only_repos = [ 
	"~/gitrepo/*/"
]

``` 
Did something change? Why i get this error now ? 

My version of topgrade is ``14.0.1``
