### ISSUE TITLE
pre_sudo doesn't cache credentials with GSudo

### ISSUE THREAD

**Issue by Andreas02-dev** [topgrade-rs/topgrade#1057]
## Erroneous Behavior

When GSudo is used with [PathPrecedence](https://github.com/gerardog/gsudo/blob/master/docs/docs/gsudo-vs-sudo.md#user-experience) set to true, `pre-sudo` doesn't cache the credentials.

## Expected Behavior

`pre-sudo` caches credentials correctly with GSudo when PathPrecedence is enabled.

## Steps to reproduce

1. On a recent Windows 11 version, install GSudo and set PathPrecedence to true as mentioned in [PathPrecedence](https://github.com/gerardog/gsudo/blob/master/docs/docs/gsudo-vs-sudo.md#user-experience).
2. Enable `pre-sudo` in `topgrade.toml`
3. Run topgrade without admin, and verify that `sudo -v` is executed instead of `sudo echo`.

topgrade.toml
```toml
[misc]
# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
pre_sudo = true
```

## Possible Cause (Optional)

Since the `sudo` binary exists by default in Windows 11 now and MS `sudo` is evaluated before `GSudo` in [Sudo::detect](https://github.com/topgrade-rs/topgrade/blob/b1ffe7d5537dad5250181868f22edce0d1b78d6f/src/sudo.rs#L26), even with GSudo PathPrecedence set to true it will issue `SudoKind::Sudo` instead of `SudoKind::GSudo`.

Additionally, `gsudo status` only shows the current credential cache status and doesn't elevate & cache credentials. This should probably be changed to something that *does* require elevation, like a dummy `echo` command that other elevation tools use in `sudo.rs`.

## Problem persists without calling from topgrade

- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

## Configuration file (Optional)

Relevant part:
```toml
[misc]
# Run `sudo -v` to cache credentials at the start of the run
# This avoids a blocking password prompt in the middle of an unattended run
# (default: false)
pre_sudo = true
```

## Additional Details
- Operation System/Version
  

Windows 11, version 24H2 build 26100.3194

- Installation
  

Winget

- Topgrade version (`topgrade -V`)

topgrade 16.0.2

## Verbose Output (`topgrade -v`)

<details>
<pre>
── 20:01:01 - Self update ──────────────────────────────────────────────────────
Checking target-arch... x86_64-pc-windows-msvc
Checking current version... v16.0.2
Checking latest released version... DEBUG starting new connection: https://api.github.com/
DEBUG resolving host="api.github.com"
DEBUG connecting to 140.82.121.5:443
DEBUG connected to 140.82.121.5:443
DEBUG No cached session for DnsName("api.github.com")
DEBUG Not resuming any session
DEBUG Using ciphersuite TLS13_AES_128_GCM_SHA256
DEBUG Not resuming
DEBUG TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(687474702f312e31)])]
DEBUG ALPN protocol is Some(b"http/1.1")
DEBUG pooling idle connection for ("https", api.github.com)
v16.0.2
Topgrade is up-to-date

── 20:01:01 - Sudo ─────────────────────────────────────────────────────────────
DEBUG Executing command `C:\Program Files\gsudo\Current\sudo.exe -v`
gsudo v2.6.0 (Branch.tags-v2.6.0.Sha.8067a30b9a83dc3ba318c0007644d1878773abec)
Copyright(c) 2019-2022 Gerardo Grignoli and GitHub contributors
</pre>
</details>
