### ISSUE TITLE
sudo_command config is not working and it is using please as sudo command by default

### ISSUE THREAD

**Issue by Kunal2007-web** [topgrade-rs/topgrade#483]
## Erroneous Behavior
I see this error message:
`ERROR Failed to deserialize /home/kunal/.config/topgrade.toml: unknown field `sudo_command`, expected one of `pre_sudo`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `display_time`, `assume_yes`, `yay_arguments`, `aura_aur_arguments`, `aura_pacman_arguments`, `no_retry`, `run_in_tmux`, `cleanup`, `notify_each_step`, `accept_all_windows_updates`, `skip_notify`, `bashit_branch`, `only`, `no_self_update` for key `misc` at line 45 column 1

── 17:35:20 - Self update ──────────────────────────────────────────────────────
Topgrade is up-to-date

── 17:35:21 - System update ────────────────────────────────────────────────────
Usage: please [OPTIONS] COMMAND [ARGS]...
Try 'please --help' for help.

Error: No such command '/usr/bin/dnf'.
System update failed: 
   0: Command failed: `/home/kunal/.local/bin/please /usr/bin/dnf upgrade`
   1: `/home/kunal/.local/bin/please` failed: exit status: 2

Location:
   src/steps/os/linux.rs:225

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit`

## Expected Behavior
I expected to run properly using sudo and not using please.

## Steps to reproduce
use this config file and run topgrade on fedora 38:

## Possible Cause (Optional)
it is not reading the `sudo_command` variable right

## Problem persists without calling from topgrade

- [ ] Yes
- [ x] No

## Configuration file (Optional)

```toml
# Topgrade Configuration - Kunal Kumar
[misc]
# Disable specific steps - same options as the command line flag
disable = ["vim", "emacs", "node"]

# Do not ask to retry failed steps (default: false)
no_retry = false

# Run `sudo -v` to cache credentials at the start of the run; this avoids a
# blocking password prompt in the middle of a possibly-unattended run.
pre_sudo = false

# set sudo command
sudo_command = "sudo"

# set the terminal title
set_title = true

# Display the time in step titles
display_time = true

# Cleanup temporary or old files
cleanup = true

# Skip sending a notification at the end of a run
skip_notify = false

[git]
max_concurrency = 5
# Additional git repositories to pull
repos = []

# Commands to run before anything
[pre_commands]
"Title" = "figlet -c Topgrade"

[npm]
# Use sudo if the NPM directory isn't owned by the current user
use_sudo = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = true

[flatpak]
# Use sudo for updating the system-wide installation
use_sudo = true
```

## Additional Details
- Operation System/Version
  Fedora Linux 38, using ZSH Shell

- Installation
  Installed from repository release

- Topgrade version (`topgrade -V`)
  Topgrade 12.0.0
## Verbose Output (`topgrade -v`)

<details>
<pre>
DEBUG Configuration at /home/kunal/.config/topgrade.toml
ERROR Failed to deserialize /home/kunal/.config/topgrade.toml: unknown field `sudo_command`, expected one of `pre_sudo`, `git_repos`, `predefined_git_repos`, `disable`, `ignore_failures`, `remote_topgrades`, `remote_topgrade_path`, `ssh_arguments`, `git_arguments`, `tmux_arguments`, `set_title`, `display_time`, `assume_yes`, `yay_arguments`, `aura_aur_arguments`, `aura_pacman_arguments`, `no_retry`, `run_in_tmux`, `cleanup`, `notify_each_step`, `accept_all_windows_updates`, `skip_notify`, `bashit_branch`, `only`, `no_self_update` for key `misc` at line 45 column 1
DEBUG Loaded configuration: ConfigFile { include: None, misc: None, sudo_command: None, pre_commands: None, post_commands: None, commands: None, python: None, composer: None, brew: None, linux: None, git: None, windows: None, npm: None, yarn: None, vim: None, firmware: None, vagrant: None, flatpak: None, distrobox: None }
DEBUG Version: 12.0.0
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "-v"] }
DEBUG Binary path: Ok("/home/kunal/bin/topgrade")
DEBUG Self Update: true
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/kunal/.config/emacs" doesn't exist
DEBUG Path "/home/kunal/.emacs.d" doesn't exist
DEBUG Cannot find "doas"
DEBUG Detected "/home/kunal/.local/bin/please" as "please"

── 17:44:21 - Self update ──────────────────────────────────────────────────────
DEBUG starting new connection: https://api.github.com/    
DEBUG resolving host="api.github.com"
DEBUG connecting to 20.207.73.85:443
DEBUG connected to 20.207.73.85:443
DEBUG No cached session for DnsName("api.github.com")    
DEBUG Not resuming any session    
DEBUG Using ciphersuite TLS13_AES_128_GCM_SHA256    
DEBUG Not resuming    
DEBUG TLS1.3 encrypted extensions: [ServerNameAck, Protocols([ProtocolName(6832)])]    
DEBUG ALPN protocol is Some(b"h2")    
DEBUG binding client connection
DEBUG client connection bound
DEBUG send frame=Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
DEBUG Connection{peer=Client}: new
DEBUG Connection{peer=Client}: send frame=WindowUpdate { stream_id: StreamId(0), size_increment: 5177345 }
DEBUG pooling idle connection for ("https", api.github.com)
DEBUG Connection{peer=Client}: send frame=Headers { stream_id: StreamId(1), flags: (0x5: END_HEADERS | END_STREAM) }
DEBUG Connection{peer=Client}: received frame=Settings { flags: (0x0), max_concurrent_streams: 100, initial_window_size: 67108864, max_frame_size: 65536, enable_connect_protocol: 1 }
DEBUG Connection{peer=Client}: send frame=Settings { flags: (0x1: ACK) }
DEBUG Connection{peer=Client}: received frame=Settings { flags: (0x1: ACK) }
DEBUG Connection{peer=Client}: received settings ACK; applying Settings { flags: (0x0), enable_push: 0, initial_window_size: 2097152, max_frame_size: 16384 }
DEBUG Connection{peer=Client}: received frame=Headers { stream_id: StreamId(1), flags: (0x4: END_HEADERS) }
DEBUG Connection{peer=Client}: received frame=Data { stream_id: StreamId(1) }
DEBUG Connection{peer=Client}: received frame=Data { stream_id: StreamId(1), flags: (0x1: END_STREAM) }
DEBUG Connection{peer=Client}: close
Topgrade is up-to-date
DEBUG Step "packer.nu"
DEBUG Step "System update"

── 17:44:21 - System update ────────────────────────────────────────────────────
DEBUG Cannot find "rpm-ostree"
DEBUG Detected "/usr/bin/dnf" as "dnf"
DEBUG Executing command `/home/kunal/.local/bin/please /usr/bin/dnf upgrade`
Usage: please [OPTIONS] COMMAND [ARGS]...
Try 'please --help' for help.

Error: No such command '/usr/bin/dnf'.
DEBUG Command failed: Err(
   0: Command failed: `/home/kunal/.local/bin/please /usr/bin/dnf upgrade`
   1: `/home/kunal/.local/bin/please` failed: exit status: 2

Location:
   src/steps/os/linux.rs:225

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.)
DEBUG Step "System update" failed: 
   0: Command failed: `/home/kunal/.local/bin/please /usr/bin/dnf upgrade`
   1: `/home/kunal/.local/bin/please` failed: exit status: 2

Location:
   src/steps/os/linux.rs:225

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
System update failed: 
   0: Command failed: `/home/kunal/.local/bin/please /usr/bin/dnf upgrade`
   1: `/home/kunal/.local/bin/please` failed: exit status: 2

Location:
   src/steps/os/linux.rs:225

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Retry? (y)es/(N)o/(s)hell/(q)uit
</pre>
</details>

**Comment by SteveLauC** [comment]
`sudo_command` actually does not belong to the section `[misc]`, the [config example file](https://github.com/topgrade-rs/topgrade/blob/master/config.example.toml) is wrong...

PR #484 fixed this by moving it to the section `[misc]`, before the new release, you could configure Topgrade like this:

```toml
# Topgrade Configuration - Kunal Kumar

sudo_command = "sudo"

# Your other configuration entries

[misc]
```
