### ISSUE TITLE
topgrade --only toolbox erroring. Have no idea why

### ISSUE THREAD

**Issue by msmafra** [topgrade-rs/topgrade#644]
## Erroneous Behavior
Running topgrade or topgrade --only toolbox errors out.

## Expected Behavior
To not error out updating cleanly

## Steps to reproduce
Have some random images like: ubuntu, debian12, Fedora 38. After a while not used the error started with topgrade.

## Possible Cause (Optional)
I have no idea what's happening. I barely use those image, so I even deleted all images using podman and the error persist.

## Problem persists without calling from topgrade
Don't know what to test here.
- [x] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml
[misc]
# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
#disable = ["system", "emacs"]
disable = ["atom", "composer", "tmux"]

# Ignore failures for these steps
#ignore_failures = ["powershell"]

# Run specific steps - same options as the command line flag
#only = ["system", "emacs"]

# Do not ask to retry failed steps (default: false)
#no_retry = true
no_retry = true

# Run inside tmux
#run_in_tmux = true

# List of remote machines with Topgrade installed on them
#remote_topgrades = ["toothless", "pi", "parnas"]

# Arguments to pass SSH when upgrading remote systems
#ssh_arguments = "-o ConnectTimeout=2"

# Path to Topgrade executable on remote machines
#remote_topgrade_path = ".cargo/bin/topgrade"

# Arguments to pass tmux when pulling Repositories
#tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title
#set_title = false
set_title = true

# Cleanup temporary or old files
#cleanup = true
cleanup = true

[git]
#max_concurrency = 5
# Additional git repositories to pull
#repos = [
#    "~/src/*/",
#    "~/.config/something"
#]

# Don't pull the predefined git repos
#predefined_repos = false

# Arguments to pass Git when pulling Repositories
#arguments = "--rebase --autostash"

[composer]
self_update = true

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"

[brew]
#greedy_cask = true

[linux]
# Arch Package Manager to use. Allowed values: autodetect, trizen, paru, yay, pacman.
#arch_package_manager = "pacman"
# Arguments to pass yay (or paru) when updating packages
#yay_arguments = "--nodevel"
#show_arch_news = true
#trizen_arguments = "--devel"
#enable_tlmgr = true
#emerge_sync_flags = "-q"
#emerge_update_flags = "-uDNa --with-bdeps=y world"
redhat_distro_sync = true
rpm_ostree = false

[windows]
# Manually select Windows updates
#accept_all_updates = false
#open_remotes_in_new_terminal = true

# Causes Topgrade to rename itself during the run to allow package managers
# to upgrade it. Use this only if you installed Topgrade by using a package
# manager such as Scoop to Cargo
#self_rename = true

[npm]
# Use sudo if the NPM directory isn't owned by the current user
#use_sudo = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
#upgrade = true

[flatpak]
# Use sudo for updating the system-wide installation
#use_sudo = true


```

## Additional Details
- Operation System/Version
  

- Installation
  

- Topgrade version (`topgrade -V`)

## Verbose Output (`topgrade -v`)
~
 .056ns fsh ❯ topgrade --only toolbx --verbose
DEBUG Configuration at /home/marcelo/.config/topgrade.toml
DEBUG Version: 13.0.0
DEBUG OS: x86_64-unknown-linux-gnu
DEBUG Args { inner: ["topgrade", "--only", "toolbx", "--verbose"] }
DEBUG Binary path: Ok("/home/marcelo/.cargo/bin/topgrade")
DEBUG self-update Feature Enabled: false
DEBUG Configuration: Config { opt: CommandLineArgs { edit_config: false, show_config_reference: false, run_in_tmux: false, cleanup: false, dry_run: false, no_retry: false, disable: [], only: [Toolbx], custom_com
DEBUG Detected "/usr/bin/git" as "git"
DEBUG Cannot find "pwsh"
DEBUG Cannot find "powershell"
DEBUG Path "/home/marcelo/.config/emacs" doesn't exist
DEBUG Path "/home/marcelo/.emacs.d" doesn't exist
DEBUG Detected "/usr/bin/doas" as "doas"
DEBUG Step "toolbx"
DEBUG Detected "/usr/bin/toolbox" as "toolbox"

── 11:32:12 - Toolbx ───────────────────────────────────────────────────────────
DEBUG Executing command `/usr/bin/toolbox list --containers`
DEBUG Toolboxes to inspect: []
DEBUG /home/marcelo/.ideavimrc does not exist
DEBUG /home/marcelo/.intellimacs does not exist
DEBUG /home/marcelo/.zshrc is a file. Checking /home/marcelo
DEBUG Checking if /home/marcelo is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/git rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
   1: `/usr/bin/git` failed: exit status: 128

Location:
   /home/marcelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/git.rs:208)
DEBUG Checking if /home/marcelo/.config/fish is a git repository
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
DEBUG Command failed: Err(
   0: Command failed: `/usr/bin/git rev-parse --show-toplevel`

      Stderr:
      fatal: not a git repository (or any parent up to mount point /)
      Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
   1: `/usr/bin/git` failed: exit status: 128

Location:
   /home/marcelo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/topgrade-13.0.0/src/steps/git.rs:208)
DEBUG /home/marcelo/.config/openbox does not exist
DEBUG /home/marcelo/.config/bspwm does not exist
DEBUG /home/marcelo/.config/i3 does not exist
DEBUG /home/marcelo/.config/sway does not exist

── 11:32:12 - Summary ──────────────────────────────────────────────────────────
toolbx: OK
DEBUG Desktop notification: Topgrade finished successfully
 INFO perform: new
 INFO perform:write_command{command=Auth(Some(External), Some([49, 48, 48, 48]))}: new
 INFO perform:write_command{command=Auth(Some(External), Some([49, 48, 48, 48]))}: close
 INFO perform:read_command: new
 INFO perform:read_command: close
 INFO perform:write_command{command=NegotiateUnixFD}: new
 INFO perform:write_command{command=NegotiateUnixFD}: close
 INFO perform:read_command: new
 INFO perform:read_command: close
 INFO perform:write_command{command=Begin}: new
 INFO perform:write_command{command=Begin}: close
 INFO perform: close
 INFO socket reader: new

<details>
<pre>

</pre>
</details>
