### ISSUE TITLE
Intelligently-enabled custom commands

### ISSUE THREAD

**Issue by 9999years** [topgrade-rs/topgrade#683]
Topgrade supports custom commands, like this:

```toml
[commands]
"Home Mangler" = "home-mangler --update --verbose"
```

Unfortunately, unlike the built-in steps, this command will always be run, and will fail if `home-mangler` isn't installed. As I often run Topgrade on various machines in varying states of disrepair, these sorts of failures are annoying.

It would be nice if I could require that a given command be installed:

```toml
[[commands]]
name = "Home Mangler"
requires = ["home-mangler"]
command = "home-mangler --update --verbose"
```

Then, the "Home Mangler" step would only run if there exists a `home-mangler` binary on the `$PATH`.
