### ISSUE TITLE
Git support fetch only

### ISSUE THREAD

**Issue by clinta** [topgrade-rs/topgrade#806]
An option to only fetch git repos instead of pulling them would be appreciated. I do not want my git working directory changed by topgrade. But a git fetch would be useful so I can instantly pull in the future.

**Comment by SteveLauC** [comment]
This looks like a reasonable feature, I think we can have a configuration entry to enable it:

```toml
[git]
# How many repos to pull at max in parallel
# max_concurrency = 5

# Additional git repositories to pull
# repos = [
#     "~/src/*/",
#     "~/.config/something"
# ]

# Don't pull the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling Repositories
# arguments = "--rebase --autostash"

# If enabled, Topgrade only `git fetch`s the specified repositories instead of pulling them
fetch_only = false 
```
