### ISSUE TITLE
Feature: Support mise

### ISSUE THREAD

**Issue by rubiin** [topgrade-rs/topgrade#841]
## I want to suggest a new step

https://github.com/jdx/mise

Since we are supporting asdf , mise would be a nice addition

For now , I am doing via custom commands

```toml
  # Custom commands
  [commands]
"Mise" = "mise self-update;mise plugins update"

```

## I want to suggest some general feature
Topgrade should...

should update mise plugins. Should self upgrade mise
