### ISSUE TITLE
Additional Git repositories not expanding environment variables like `$HOME`

### ISSUE THREAD

**Issue by j-lakeman** [topgrade-rs/topgrade#921]
## Erroneous Behavior
Within the `[git]` section of `topgrade.toml`,

`repos = ["/home/xxx/Documents/Git/*"]` is expanded, whereas

`repos = ["$HOME/Documents/Git/*"]` as well as
`repos = ["~/Documents/Git/*"]` or
`repos = ["$GIT/*"]` don't expand.

## Expected Behavior
all of the above expand properly (subdirectories of Git/ as well as environment variables)

## Steps to reproduce
alter `topgrade.toml` accordingly

## Possible Cause (Optional)
shell or topgrade don't expand variables

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

## Configuration file (Optional)
```toml
[git]
# How many repos to pull at max in parallel
# max_concurrency = 5

# Additional git repositories to pull
repos = ["~/Documents/Git/*"]

# Don't pull the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling Repositories
arguments = "--autostash"
```

## Additional Details
- Operation System/Version
openSUSE Tumbleweed, Debian Sid, macOS

- Installation
 package manager (zypper, apt, brew)

- Topgrade version (`topgrade -V`)
Topgrade 15.0.0 
## Verbose Output (`topgrade -v`)
<details>
<pre>
DEBUG Executing command `/usr/bin/git rev-parse --show-toplevel`
Path ~/Documents/Git/* did not contain any git repositories
</pre>
</details>

I should probably also mention that I'm tracking my entire home directory with Git, so the Git directories above are nested.
