### ISSUE TITLE
bootc exists on system but disabled via config will ignore rpm-ostree

### ISSUE THREAD

**Issue by befanyt** [topgrade-rs/topgrade#997]
## Erroneous Behavior

Tried to update my system. With `rpm-ostree=true` and `bootc=false` (default). My system has bootc on it, so it found it but it is disabled via config and tries to update via `dnf` now.

## Expected Behavior

topgrade should have used `rpm-ostree` to update the system

## Steps to reproduce

Update the system with topgrade, where bootc is available but disabled on the system.

## Possible Cause (Optional)

https://github.com/topgrade-rs/topgrade/blob/4df30c25878ee3713152ea6cf3f4ce4225336fd6/src/steps/os/linux.rs#L233
I think that needs to be just an if statement, and not if else. Because bootc is found, then checks config which is disabled. Because bootc exists it will never go into the rpm-ostree flow when it finds out that it is disabled via config.

## Problem persists without calling from topgrade

- [ ] Yes
- [x] No

## Did you run topgrade through `Remote Execution`

- [ ] Yes
- [x] No

If yes, does the issue still occur when you run topgrade directlly in your
remote host

- [ ] Yes
- [ ] No

## Configuration file (Optional)

```toml
[misc]
no_self_update = true
only = ["system", "flatpak", "distrobox", "firmware"]
disable = ["self_update", "toolbx", "containers", "helm"]
ignore_failures = ["distrobox", "flatpak", "brew_cask", "brew_formula", "nix", "node", "pip3", "home_manager", "firmware"]
assume_yes = true
no_retry = false

[linux]
rpm_ostree = true
```

## Additional Details
- Operation System/Version
  
Universal Blue Bluefin 
- Installation
  
Via pip I think, its included in bluefin
- Topgrade version (`topgrade -V`)
`topgrade 16.0.2`
## Verbose Output (`topgrade -v`)

<details>
<pre>
── 14:44:42 - System update ────────────────────────────────────────────────────
DEBUG Detected "/usr/bin/bootc" as "bootc"
DEBUG Detected "/usr/bin/dnf" as "dnf"
DEBUG Executing command `/usr/bin/sudo /usr/bin/dnf upgrade`
</pre>
</details>
